### PR TITLE
readme: Include browser support information

### LINKED ISSUE #197: Browser support info
It would be nice to have info in docs about browser support. 

BTW Does it support IE11?
Judging by [Workers](https://developer.mozilla.org/en-US/docs/Web/API/Worker) support it does, but it can be limited.

### PR DESCRIPTION
**Pull request by kamalmarhubi**
Lifted from the Comlink readme, where the relevant
lines have not changed in almost 18 months:
https://github.com/GoogleChromeLabs/comlink/blame/89dc29d9382228ea2b0d6150dc1c4e6cadacf2b6/README.md#L13-L22

closes #197

### CODE REVIEW

**Comment by kamalmarhubi** [comment]
Sorry miclicked. Was going to ping @surma :-)

**Comment by surma** [comment]
Sorry! I’m currently swamped to prepare for JamStackConf. I’ll get back to this later in teh week!

**Comment by Ishaan28malik** [comment]
@surma have you updated this ?

**Comment by kamalmarhubi** [comment]
@surma @Ishaan28malik I'm going through and tidying up my hanging PRs. Do you think this is likely to get merged in the next week or so?

**Comment by surma** [comment]
Not in the next 2 weeks as I am on vacation :) I’ll get around to it after, hopefully. But feel free to close and I’ll whip up my own. Thanks for your patience.

**Comment by kamalmarhubi** [comment]
Ah that's fine. Enjoy vacation! And I'll ping this again some time in second week of September. :-)

**Comment by kamalmarhubi** [comment]
@surma forgot to check in, hope you had a good vacation :-)

**Comment by surma** [comment]
Sorry things took so long! Cheers for this!

**Pull request merged**
